### ISSUE TITLE
Als leverancier wil ik mijn api-client kunnen testen

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#3]
zodat ik zeker weet dat ik de provider-api goed kan aanroepen en ik de client-applicatie goed kan laten werken.

zie #36

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by HenriKorver** [comment]
Het is de verantwoordelijkheid van de beheerder van de te testen API om een referentie-implementatie op te leveren conform DoD. Dus een leverancier kan in principe zijn client testen tegen de referentie-implementatie (de provider api). De vraag is wat hier de toegevoegde waarde is van een centrale testvoorziening.

**Comment by melsk-r** [comment]
> 
> 
> Het is de verantwoordelijkheid van de beheerder van de API om een referentie-implementatie op te leveren conform DoD. Dus een leverancier kan in principe zijn client testen tegen deze referentie-implementatie (de provider api). De vraag is wat hier de toegevoegde waarde is van een centrale testvoorziening.

Ik neem aan dat je hier niet de API bedoelt maar de Open API standaard. Daarnaast is dit n.m.m. niet de verantwoordelijkheid van de **Beheerder** van de Open API standaard maar van de ontwikkelaar van de Open API standaard. Het is de verantwoordelijkheid van de Beheerder van de Open API standaard dat de referentie implementatie blijft doen waarvoor hij ooit ontwikkeld is en gelijke tred houdt met de doorontwikkeling van de Open API standaard.

**Comment by HenriKorver** [comment]
Er zijn nu twee mogelijkheden voor het gebruiken van de referentie-implementatie (RI) als provider api om consumers te testen:
* de hoste versie van de RI op een externe server van de beheer van de api standaard
* de RI als docker-container op de lokale computer van de leverancier

In het eerste geval kunnen tests met elkaar conflicteren als meerder clients tegelijk getest worden op de gehoste versie van de RI. In dit geval zou de testvoorziening faciliteiten kunnen bieden om in de cloud dynamisch per test een aparte docker-containers op te starten en na de test te beeindigen.
