### ISSUE TITLE
Als gemeente wil ik dat provider-applicaties voldoen aan de standaard

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#37]
zodat ik zeker weet dat de provider-applicatie zijn taken goed kan uitvoeren.

**Toelichting**:
Als een gemeente bijvoorbeeld een zaaksysteem gaat kopen dan wil de gemeente zeker weten of de API van dat zaaksysteem voldoet aan ZDS-standaard.

**Oplossingsrichting**:
We gaan ervan uit dat de testscenario's om de provider te testen worden aangeleverd vanuit de beheerder van de API-standaard, in dit voorbeeld de ZDS-standaard.
De TV zorgt ervoor dat deze scenario's uitgetest kunnen worden op de provider. Na dat er een start-signaal is uitgestuurd worden er vanuit de TV geautomatiseerd één of meerdere scenario's  afgevuurd op de provider. Mogelijke voorbeelden van testopdrachten in de context van ZDS:
1. Maak een zaak aan met identificatie "12345" van het zaaktype "MOR" en geef een willekeurige geometrie mee.
1. Wijs de behandelaar  `Jan de Vries` toe aan de zaak `zaken\12345` en .zet de status op `in behandeling`.
1. Voeg aan deze zaak een document toe met als titel "Wateroverlast".
1. Voeg een besluit toe met besluitidentificatie "34455677".
1. Haal het bovengenoemde besluit op.
1. Sluit de zaak af.

De scenario's kunnen uit meerdere stappen bestaan. B.v. in scenario 2 zal eerste de uri van de behandelaar opgehaald moeten worden met een GET-request alvorens de behandelaar met een POST-operatie aan de zaak gekoppeld kan worden.

De TV kan twee soorten van validatie uitvoeren:
1. Validatie op de uitvoering. Per stap wordt het volgende getest:
   * De goede fout-  (4.xx / 5.xx)  of  succesmeldingen (2.xx) worden teruggegeven. 
NB: hierin verschilt het testen van de provider in plaats van de client. Bij het testen van de provider is het nuttig om ook op foutsituaties te testen.
   * Responses voldoen aan de gestelde eisen qua headers en berichtinhoud.

2. Validatie op het eindresultaat. Door middel van bijvoorbeeld GET-requests kan de TV checken of de gewenste eindtoestand bij de provider is bereikt nadat de client de testopdracht(en) heeft doorlopen.

Uiteindelijk moet de TV een rapportage van de uitgevoerde tests opgevraagd kunnen worden door middel van een api.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] De provider moet ook gedeeltelijk getest kunnen worden
- [ ] ...
- [ ] ...

**Taken**
- [ ] Vaststellen welke userscenario's we gaan gebruiken in het prototype
- [ ] Ontwikkelen prototype
- [ ] Uittesten en reviewen prototype
- [ ] Opstellen specificatie voor de aanbesteding

**Comment by melsk-r** [comment]
Je schrijft:

> **Oplossingsrichting:**
> We gaan ervan uit dat de testscenario's om de provider te testen worden aangeleverd vanuit de beheerder van de API-standaard, in dit voorbeeld de ZDS-standaard.

Hiervoor geldt natuurlijk hetzelfde als opgemerkt bij issue #36
